import java.sql.SQLOutput;
import java.util.Hashtable;
import java.util.Random;

import static java.lang.System.currentTimeMillis;

public class HashTest {

    private static String dataType, debug = "";
    private static int insert, randNum = 0;
    private static double alpha;
    private static Random rand = new Random();

    public static void main(String[] args) {

        if (args.length < 2) {
            help();
            System.exit(0);
        }
        dataType = args[0];
        alpha = Double.parseDouble(args[1]);
        if (args.length == 3) {
            debug = args[2];
        }
        PrimeCheck prime = new PrimeCheck(95500, 96000);
        //int size = prime.getPrime();
        int size = 95791;
        HashTable linearTable = new HashTable(size, HashTable.HashType.LINEAR);
        HashTable doubleTable = new HashTable(size, HashTable.HashType.DOUBLE);
        while(alpha != insert/size) {
            if (dataType == "1") {
                //Integer object using Random integer is created using nextInt()
                randNum = rand.nextInt();
                HashObject<Integer> obj = new HashObject<>(randNum);
                linearTable.add(obj);
                doubleTable.add(obj);
                insert++;
            } else if (dataType == "2") {
                //Long Object generated by System.currentTimeMillis()
                long num = currentTimeMillis();
                HashObject<Long> obj = new HashObject<>(num);
                linearTable.add(obj);
                doubleTable.add(obj);
                insert++;
            } else if (dataType == "3") {
                //Contains a word from the list /home/JHyeh/cs321/lab/lab3/files
            } else {
                System.out.println("Incorrect Input Type");
                help();
                System.exit(0);
            }
        }

    }

    private static void help() {
        System.out.println("---Incorrect arguments ---");
        System.out.println("Usage: java HashTest <input type> <load factor> [<debug level>]");
        System.out.println("Input type: 1, 2, 3");
        System.out.println("Load Factor: 0 < x < 1");
        System.out.println("[Debug level: 0 (primary summary) or 1 (summary with hashtable, # of duplicates/probes into a files]");
    }
}